[package]
name = "dualshock-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "2.6.0"
async-std = {version = "1.12.0", features = ["attributes"]}